from __future__ import annotations

from enum import Enum


class WorkflowEvent(str, Enum):
    JOB_FOUND = "JOB_FOUND"
    TRACKER_SYNC_REQUESTED = "TRACKER_SYNC_REQUESTED"
    EMAIL_RECEIVED = "EMAIL_RECEIVED"
    FOLLOW_UP_TASK_CREATED = "FOLLOW_UP_TASK_CREATED"
    STRATEGY_REFLECTED = "STRATEGY_REFLECTED"
    APPLICATION_GENERATED = "APPLICATION_GENERATED"
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    RESUME_TAILORED = "RESUME_TAILORED"
    FOLLOW_UP_SENT = "FOLLOW_UP_SENT"
